# Generated by Django 4.1.4 on 2022-12-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0005_alter_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
