# Generated by Django 4.1.4 on 2022-12-11 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0006_alter_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None),
        ),
    ]
