# Generated by Django 4.1.4 on 2022-12-12 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0007_alter_task_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='task',
            name='record_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='record_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
